# -*- coding: utf-8 -*-
"""Apple Stock Data - DV Week 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l6vbyb1G26j0N8p0ajtHv3Yqhi3-U5tM
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Apple_historical_data.csv")

df

print (df.head())

print (df.info())

df = df.dropna()
df = df.drop_duplicates()
df