# -*- coding: utf-8 -*-
"""Super Store Sales Data - DV Week 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zDYND_joaX_Usu2_TC7jXSjxadzDy5D_
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/samplesuperstore - samplesuperstore.csv.xls")

df.head()

df.info()

df.describe()



